INSERT INTO event_managment.t_002_state_types (name) VALUES ('Users');
INSERT INTO event_managment.t_002_state_types (name) VALUES ('Events');
INSERT INTO event_managment.t_002_state_types (name) VALUES ('Roles');

INSERT INTO event_managment.t_002_states (name, state_type) VALUES ('Available', 1);
INSERT INTO event_managment.t_002_states (name, state_type) VALUES ('Event assigned', 1);
INSERT INTO event_managment.t_002_states (name, state_type) VALUES ('Busy', 1);
INSERT INTO event_managment.t_002_states (name, state_type) VALUES ('Unavailable', 1);

INSERT INTO event_managment.t_002_states (name, state_type) VALUES ('Created', 2);
INSERT INTO event_managment.t_002_states (name, state_type) VALUES ('Pending', 2);
INSERT INTO event_managment.t_002_states (name, state_type) VALUES ('Assigned', 2);
INSERT INTO event_managment.t_002_states (name, state_type) VALUES ('Accepted', 2);
INSERT INTO event_managment.t_002_states (name, state_type) VALUES ('In proccess', 2);
INSERT INTO event_managment.t_002_states (name, state_type) VALUES ('On hold', 2);
INSERT INTO event_managment.t_002_states (name, state_type) VALUES ('Rejected', 2);
INSERT INTO event_managment.t_002_states (name, state_type) VALUES ('Solved', 2);
INSERT INTO event_managment.t_002_states (name, state_type) VALUES ('Verification', 2);
INSERT INTO event_managment.t_002_states (name, state_type) VALUES ('Archived', 2);
INSERT INTO event_managment.t_002_states (name, state_type) VALUES ('Validated', 2);

INSERT INTO event_managment.t_002_states (name, state_type) VALUES ('Active', 3);
INSERT INTO event_managment.t_002_states (name, state_type) VALUES ('Inactive', 3);

INSERT INTO event_managment.t_002_categories (name) VALUES ('Pánico');
INSERT INTO event_managment.t_002_categories (name) VALUES ('Emergencia');
INSERT INTO event_managment.t_002_categories (name) VALUES ('Accidente');
INSERT INTO event_managment.t_002_categories (name) VALUES ('Vehículo varado');
INSERT INTO event_managment.t_002_categories (name) VALUES ('Falla vehículo');
INSERT INTO event_managment.t_002_categories (name) VALUES ('Vehículo faltante');
INSERT INTO event_managment.t_002_categories (name) VALUES ('Regulación de vehículo');
INSERT INTO event_managment.t_002_categories (name) VALUES ('Vehículo en IBIS');
INSERT INTO event_managment.t_002_categories (name) VALUES ('Novedad del operador');
INSERT INTO event_managment.t_002_categories (name) VALUES ('Otras novedades');

INSERT INTO event_managment.t_002_categories (name, base_priority, parent) VALUES ('Botón de pánico', 1000, 1);
INSERT INTO event_managment.t_002_categories (name, base_priority, parent) VALUES ('Situación urgente ', 990, 2);
INSERT INTO event_managment.t_002_categories (name, base_priority, parent) VALUES ('Vandalismo', 980, 2);
INSERT INTO event_managment.t_002_categories (name, base_priority, parent) VALUES ('Sospechoso a bordo', 970, 2);
INSERT INTO event_managment.t_002_categories (name, base_priority, parent) VALUES ('Ascenso irreg. De pasajeros', 960, 2);
INSERT INTO event_managment.t_002_categories (name, base_priority, parent) VALUES ('Accidente entre buses MIO', 800, 3);
INSERT INTO event_managment.t_002_categories (name, base_priority, parent) VALUES ('Accidente Bus MIO con terceros', 800, 3);
INSERT INTO event_managment.t_002_categories (name, base_priority, parent) VALUES ('Falla mecánica', 740, 4);
INSERT INTO event_managment.t_002_categories (name, base_priority, parent) VALUES ('Falta de gasolina o batería', 700, 4);
INSERT INTO event_managment.t_002_categories (name, base_priority, parent) VALUES ('Llanta pinchada', 700, 4);
INSERT INTO event_managment.t_002_categories (name, base_priority, parent) VALUES ('Falla aire acondicionado', 600, 5);
INSERT INTO event_managment.t_002_categories (name, base_priority, parent) VALUES ('Falla en vehículo', 600, 5);
INSERT INTO event_managment.t_002_categories (name, base_priority, parent) VALUES ('Falla comunicación FONIA', 600, 5);
INSERT INTO event_managment.t_002_categories (name, base_priority, parent) VALUES ('Fallo Motor M', 600, 5);
INSERT INTO event_managment.t_002_categories (name, base_priority, parent) VALUES ('Fallo de Aire Acond M', 600, 5);
INSERT INTO event_managment.t_002_categories (name, base_priority, parent) VALUES ('Incumplimiento detectado', 500, 6);
INSERT INTO event_managment.t_002_categories (name, base_priority, parent) VALUES ('Pronostico desviación tiempo futuro', 400, 7);
INSERT INTO event_managment.t_002_categories (name, base_priority, parent) VALUES ('desviación INMEDIATA tiempo ', 400, 7);
INSERT INTO event_managment.t_002_categories (name, base_priority, parent) VALUES ('Vía bloqueada', 400, 7);
INSERT INTO event_managment.t_002_categories (name, base_priority, parent) VALUES ('Alcance vehículo espero orden', 400, 7);
INSERT INTO event_managment.t_002_categories (name, base_priority, parent) VALUES ('Veh disponible, ubicar', 400, 7);
INSERT INTO event_managment.t_002_categories (name, base_priority, parent) VALUES ('Operación Normal ', 400, 7);
INSERT INTO event_managment.t_002_categories (name, base_priority, parent) VALUES ('Movilidad lenta', 400, 7);
INSERT INTO event_managment.t_002_categories (name, base_priority, parent) VALUES ('Irregularidad', 400, 7);
INSERT INTO event_managment.t_002_categories (name, base_priority, parent) VALUES ('Impuntualidad', 400, 7);
INSERT INTO event_managment.t_002_categories (name, base_priority, parent) VALUES ('Detección de brechas por distancia de vehículos', 400, 7);
INSERT INTO event_managment.t_002_categories (name, base_priority, parent) VALUES ('Detección de pelotones por distancia de vehículos', 400, 7);
INSERT INTO event_managment.t_002_categories (name, base_priority, parent) VALUES ('Detección de IBIS', 300, 8);
INSERT INTO event_managment.t_002_categories (name, base_priority, parent) VALUES ('Novedad otro vehículo', 200, 9);
INSERT INTO event_managment.t_002_categories (name, base_priority, parent) VALUES ('Solicitud MO-31', 200, 9);
INSERT INTO event_managment.t_002_categories (name, base_priority, parent) VALUES ('No relevo', 200, 9);
INSERT INTO event_managment.t_002_categories (name, base_priority, parent) VALUES ('Plat. Movilidad Reducida', 200, 9);
INSERT INTO event_managment.t_002_categories (name, base_priority, parent) VALUES ('Mov puertas abiertas M', 200, 9);
INSERT INTO event_managment.t_002_categories (name, base_priority, parent) VALUES ('Actividad no autorizada en vehículo', 100, 10);

INSERT INTO event_managment.t_002_step_types (name) VALUES ('Analyses');
INSERT INTO event_managment.t_002_step_types (name) VALUES ('Actions');

INSERT INTO event_managment.t_002_steps (description, step_type) VALUES ('Abrir comunicación ambiente para verificar.', 1);
INSERT INTO event_managment.t_002_steps (description, step_type) VALUES ('Ubicar vehículo con seguimiento en GIS y vista de línea.', 1);
INSERT INTO event_managment.t_002_steps (description, step_type) VALUES ('Obtener datos vehículo (No.  Vehículo y ruta).', 1);
INSERT INTO event_managment.t_002_steps (description, step_type) VALUES ('Ubicar vehículo con GIS y vista de línea.', 1);
INSERT INTO event_managment.t_002_steps (description, step_type) VALUES ('Verificar tipo de accidente.', 1);
INSERT INTO event_managment.t_002_steps (description, step_type) VALUES ('Llamar a operador: ¿hay lesionados?, ¿hay bloqueo de vía?', 1);
INSERT INTO event_managment.t_002_steps (description, step_type) VALUES ('Ubicar vehículo con GIS y vista de línea.', 1);
INSERT INTO event_managment.t_002_steps (description, step_type) VALUES ('Verificar gravedad (tipo) de falla.', 1);
INSERT INTO event_managment.t_002_steps (description, step_type) VALUES ('Verificar estado de la línea (vehículos faltantes).', 1);
INSERT INTO event_managment.t_002_steps (description, step_type) VALUES ('Revisar si hay pendiente.', 1);
INSERT INTO event_managment.t_002_steps (description, step_type) VALUES ('Revisar en IVU.Vehículo las tareas programadas.', 1);
INSERT INTO event_managment.t_002_steps (description, step_type) VALUES ('Verificar en "Horario" cual es el intervalo programado de la ruta.', 1);
INSERT INTO event_managment.t_002_steps (description, step_type) VALUES ('Definir la gravedad del faltante ( calcular % de faltantes).', 1);
INSERT INTO event_managment.t_002_steps (description, step_type) VALUES ('Revisar si se puede cubrir el espacio con EITL.', 1);
INSERT INTO event_managment.t_002_steps (description, step_type) VALUES ('Definir la necesidad de ajustar el intervalo de la ruta o adicionar tareas.', 1);
INSERT INTO event_managment.t_002_steps (description, step_type) VALUES ('Definir con el OMEGA las rutas que requieren atención y priorizar.', 1);
INSERT INTO event_managment.t_002_steps (description, step_type) VALUES ('Definir las necesidades de vehículos adicionales.', 1);
INSERT INTO event_managment.t_002_steps (description, step_type) VALUES ('Definir los cambios de ruta para cubrir adicionales.', 1);
INSERT INTO event_managment.t_002_steps (description, step_type) VALUES ('Revisar vista de línea.', 1);
INSERT INTO event_managment.t_002_steps (description, step_type) VALUES ('Confirmar ubicaciones con GIS.', 1);
INSERT INTO event_managment.t_002_steps (description, step_type) VALUES ('Verificar desviaciones horarias.', 1);
INSERT INTO event_managment.t_002_steps (description, step_type) VALUES ('Verificar el estado de operación de la ruta (contingencias).', 1);
INSERT INTO event_managment.t_002_steps (description, step_type) VALUES ('Verificar si se puede resolver con EITL (problema local).', 1);
INSERT INTO event_managment.t_002_steps (description, step_type) VALUES ('Preguntar vía texto: "indique cantidad de usuarios".', 1);
INSERT INTO event_managment.t_002_steps (description, step_type) VALUES ('Obtener cantidad de usuarios en cada vehículo.', 1);
INSERT INTO event_managment.t_002_steps (description, step_type) VALUES ('Verificar usuarios en la estación (cámaras o inspector).', 1);
INSERT INTO event_managment.t_002_steps (description, step_type) VALUES ('Considerar la hora del día y la demanda de la ruta.', 1);
INSERT INTO event_managment.t_002_steps (description, step_type) VALUES ('Analizar la necesidad de autorizar sobrepaso.', 1);
INSERT INTO event_managment.t_002_steps (description, step_type) VALUES ('Revisar si hay registro en plantilla de control de actividades operativas pendientes.', 1);
INSERT INTO event_managment.t_002_steps (description, step_type) VALUES ('Revisar si hay registro en Bitácora.', 1);
INSERT INTO event_managment.t_002_steps (description, step_type) VALUES ('Revisar si hay vehículo asignado en IVU.Vehículo', 1);
INSERT INTO event_managment.t_002_steps (description, step_type) VALUES ('Llamar al COT si hay asignación de vehículo y/o validar información', 1);
INSERT INTO event_managment.t_002_steps (description, step_type) VALUES ('Si hay asignación en IVU.Vehículo intentar establecer comunicación.', 1);
INSERT INTO event_managment.t_002_steps (description, step_type) VALUES ('Definir si es o no incumplimiento.', 1);
INSERT INTO event_managment.t_002_steps (description, step_type) VALUES ('Informar vía texto mensaje de recibido al operador.', 1);
INSERT INTO event_managment.t_002_steps (description, step_type) VALUES ('Verificar criticidad del mensaje.', 1);
INSERT INTO event_managment.t_002_steps (description, step_type) VALUES ('Ubicar vehículo con GIS y vista de línea.', 1);
INSERT INTO event_managment.t_002_steps (description, step_type) VALUES ('Verificar estado de la línea.', 1);
INSERT INTO event_managment.t_002_steps (description, step_type) VALUES ('Definir el tipo de respuesta según el mensaje recibido.', 1);
INSERT INTO event_managment.t_002_steps (description, step_type) VALUES ('Ubicar vehículo en el GIS y con vista de línea.', 1);
INSERT INTO event_managment.t_002_steps (description, step_type) VALUES ('Verificar estado de la línea y vehículos faltantes.', 1);
INSERT INTO event_managment.t_002_steps (description, step_type) VALUES ('Verificar si hay vehículos empaquetados.', 1);
INSERT INTO event_managment.t_002_steps (description, step_type) VALUES ('Preguntar vía texto: "indique cantidad de usuarios".', 1);
INSERT INTO event_managment.t_002_steps (description, step_type) VALUES ('Obtener cantidad de usuarios del vehículo.', 1);
INSERT INTO event_managment.t_002_steps (description, step_type) VALUES ('Verificar usuarios en la estación (cámaras o inspector).', 1);
INSERT INTO event_managment.t_002_steps (description, step_type) VALUES ('Comparar desviación con intervalo de la ruta y tiempo de ciclo.', 1);
INSERT INTO event_managment.t_002_steps (description, step_type) VALUES ('Verificar si es o no conveniente que se tenga esa desviación horaria.', 1);
INSERT INTO event_managment.t_002_steps (description, step_type) VALUES ('Verificar si es un problema de programación.', 1);

INSERT INTO event_managment.t_002_protocols (category, step, step_order) VALUES (1,1,1);
INSERT INTO event_managment.t_002_protocols (category, step, step_order) VALUES (1,2,2);
INSERT INTO event_managment.t_002_protocols (category, step, step_order) VALUES (1,3,3);
INSERT INTO event_managment.t_002_protocols (category, step, step_order) VALUES (6,4,1);
INSERT INTO event_managment.t_002_protocols (category, step, step_order) VALUES (6,5,2);
INSERT INTO event_managment.t_002_protocols (category, step, step_order) VALUES (6,6,3);
INSERT INTO event_managment.t_002_protocols (category, step, step_order) VALUES (7,4,1);
INSERT INTO event_managment.t_002_protocols (category, step, step_order) VALUES (7,5,2);
INSERT INTO event_managment.t_002_protocols (category, step, step_order) VALUES (7,6,3);
INSERT INTO event_managment.t_002_protocols (category, step, step_order) VALUES (8,7,1);
INSERT INTO event_managment.t_002_protocols (category, step, step_order) VALUES (8,8,2);
INSERT INTO event_managment.t_002_protocols (category, step, step_order) VALUES (8,9,3);
INSERT INTO event_managment.t_002_protocols (category, step, step_order) VALUES (10,7,1);
INSERT INTO event_managment.t_002_protocols (category, step, step_order) VALUES (10,8,2);
INSERT INTO event_managment.t_002_protocols (category, step, step_order) VALUES (10,9,3);
INSERT INTO event_managment.t_002_protocols (category, step, step_order) VALUES (12,7,1);
INSERT INTO event_managment.t_002_protocols (category, step, step_order) VALUES (12,8,2);
INSERT INTO event_managment.t_002_protocols (category, step, step_order) VALUES (12,9,3);
INSERT INTO event_managment.t_002_protocols (category, step, step_order) VALUES (16,16,1);
INSERT INTO event_managment.t_002_protocols (category, step, step_order) VALUES (16,17,2);
INSERT INTO event_managment.t_002_protocols (category, step, step_order) VALUES (16,18,3);
INSERT INTO event_managment.t_002_protocols (category, step, step_order) VALUES (25,19,1);
INSERT INTO event_managment.t_002_protocols (category, step, step_order) VALUES (25,20,2);
INSERT INTO event_managment.t_002_protocols (category, step, step_order) VALUES (25,21,3);
INSERT INTO event_managment.t_002_protocols (category, step, step_order) VALUES (25,22,4);
INSERT INTO event_managment.t_002_protocols (category, step, step_order) VALUES (25,23,5);
INSERT INTO event_managment.t_002_protocols (category, step, step_order) VALUES (25,24,6);
INSERT INTO event_managment.t_002_protocols (category, step, step_order) VALUES (25,25,7);
INSERT INTO event_managment.t_002_protocols (category, step, step_order) VALUES (25,26,8);
INSERT INTO event_managment.t_002_protocols (category, step, step_order) VALUES (25,27,9);
INSERT INTO event_managment.t_002_protocols (category, step, step_order) VALUES (25,28,10);
INSERT INTO event_managment.t_002_protocols (category, step, step_order) VALUES (26,19,1);
INSERT INTO event_managment.t_002_protocols (category, step, step_order) VALUES (26,20,2);
INSERT INTO event_managment.t_002_protocols (category, step, step_order) VALUES (26,21,3);
INSERT INTO event_managment.t_002_protocols (category, step, step_order) VALUES (26,22,4);
INSERT INTO event_managment.t_002_protocols (category, step, step_order) VALUES (26,23,5);
INSERT INTO event_managment.t_002_protocols (category, step, step_order) VALUES (26,24,6);
INSERT INTO event_managment.t_002_protocols (category, step, step_order) VALUES (26,25,7);
INSERT INTO event_managment.t_002_protocols (category, step, step_order) VALUES (26,26,8);
INSERT INTO event_managment.t_002_protocols (category, step, step_order) VALUES (26,27,9);
INSERT INTO event_managment.t_002_protocols (category, step, step_order) VALUES (26,28,10);
INSERT INTO event_managment.t_002_protocols (category, step, step_order) VALUES (27,29,1);
INSERT INTO event_managment.t_002_protocols (category, step, step_order) VALUES (27,30,2);
INSERT INTO event_managment.t_002_protocols (category, step, step_order) VALUES (27,31,3);
INSERT INTO event_managment.t_002_protocols (category, step, step_order) VALUES (27,32,4);
INSERT INTO event_managment.t_002_protocols (category, step, step_order) VALUES (27,33,5);
INSERT INTO event_managment.t_002_protocols (category, step, step_order) VALUES (27,34,6);
INSERT INTO event_managment.t_002_protocols (category, step, step_order) VALUES (29,35,1);
INSERT INTO event_managment.t_002_protocols (category, step, step_order) VALUES (29,36,2);
INSERT INTO event_managment.t_002_protocols (category, step, step_order) VALUES (29,37,3);
INSERT INTO event_managment.t_002_protocols (category, step, step_order) VALUES (29,38,4);
INSERT INTO event_managment.t_002_protocols (category, step, step_order) VALUES (29,39,5);
INSERT INTO event_managment.t_002_protocols (category, step, step_order) VALUES (30,35,1);
INSERT INTO event_managment.t_002_protocols (category, step, step_order) VALUES (30,36,2);
INSERT INTO event_managment.t_002_protocols (category, step, step_order) VALUES (30,37,3);
INSERT INTO event_managment.t_002_protocols (category, step, step_order) VALUES (30,38,4);
INSERT INTO event_managment.t_002_protocols (category, step, step_order) VALUES (30,39,5);
INSERT INTO event_managment.t_002_protocols (category, step, step_order) VALUES (18,40,1);
INSERT INTO event_managment.t_002_protocols (category, step, step_order) VALUES (18,41,2);
INSERT INTO event_managment.t_002_protocols (category, step, step_order) VALUES (18,42,3);
INSERT INTO event_managment.t_002_protocols (category, step, step_order) VALUES (18,43,4);
INSERT INTO event_managment.t_002_protocols (category, step, step_order) VALUES (18,44,5);
INSERT INTO event_managment.t_002_protocols (category, step, step_order) VALUES (18,45,6);
INSERT INTO event_managment.t_002_protocols (category, step, step_order) VALUES (18,46,7);
INSERT INTO event_managment.t_002_protocols (category, step, step_order) VALUES (18,47,8);
INSERT INTO event_managment.t_002_protocols (category, step, step_order) VALUES (18,48,9);

INSERT INTO event_managment.t_002_steps (description, step_type) VALUES ('Informar vía IP y chat a UTR&T, SSFCI, personal en vía y COT.', 2);
INSERT INTO event_managment.t_002_steps (description, step_type) VALUES ('Registrar en bitácora', 2);
INSERT INTO event_managment.t_002_steps (description, step_type) VALUES ('Hacer seguimiento hasta establecer la continuidad del vehículo', 2);
INSERT INTO event_managment.t_002_steps (description, step_type) VALUES ('Informar vía IP y chat a la UTR&T, SSFCI, personal en vía y COT', 2);
INSERT INTO event_managment.t_002_steps (description, step_type) VALUES ('Enviar a personal de control de la operación en vía al sitio, dependiendo la situación.', 2);
INSERT INTO event_managment.t_002_steps (description, step_type) VALUES ('Definir continuidad del(os) vehículo(s) en operación.', 2);
INSERT INTO event_managment.t_002_steps (description, step_type) VALUES ('Si el vehículo sale de operación solicitar al COT restitución de vehículo.', 2);
INSERT INTO event_managment.t_002_steps (description, step_type) VALUES ('Definir trasbordo de pasajeros afectados.', 2);
INSERT INTO event_managment.t_002_steps (description, step_type) VALUES ('Generar plan de desvíos apoyado por OMEGA.', 2);
INSERT INTO event_managment.t_002_steps (description, step_type) VALUES ('Enviar plan de desvió a líneas afectadas vía texto.', 2);
INSERT INTO event_managment.t_002_steps (description, step_type) VALUES ('Informar al usuario vía Luminos, Panel Gorba y otros medios disponibles.', 2);
INSERT INTO event_managment.t_002_steps (description, step_type) VALUES ('Registrar en bitácora.', 2);
INSERT INTO event_managment.t_002_steps (description, step_type) VALUES ('Ajustar frecuencia de la(s) línea(s) (VEHÍCULO FALTANTE).', 2);
INSERT INTO event_managment.t_002_steps (description, step_type) VALUES ('Aplicar estrategias de regulación.', 2);
INSERT INTO event_managment.t_002_steps (description, step_type) VALUES ('Llamar a operador y verificar la falla.', 2);
INSERT INTO event_managment.t_002_steps (description, step_type) VALUES ('Definir continuidad del vehículo en operación.', 2);
INSERT INTO event_managment.t_002_steps (description, step_type) VALUES ('Si el vehículo sale de operación solicitar al COT restitución de vehículo.', 2);
INSERT INTO event_managment.t_002_steps (description, step_type) VALUES ('Informar al equipo de control en vía más cercano.', 2);
INSERT INTO event_managment.t_002_steps (description, step_type) VALUES ('Registrar en bitácora', 2);
INSERT INTO event_managment.t_002_steps (description, step_type) VALUES ('Ajustar frecuencia de la línea (regulación).', 2);
INSERT INTO event_managment.t_002_steps (description, step_type) VALUES ('Aplicar estrategias de regulación.', 2);
INSERT INTO event_managment.t_002_steps (description, step_type) VALUES ('Si se consideró que se puede usar EITL, aplicarlo y hacer seguimiento.', 2);
INSERT INTO event_managment.t_002_steps (description, step_type) VALUES ('Si se requiere ajustar intervalo, redefinir desviaciones horarias para buses.', 2);
INSERT INTO event_managment.t_002_steps (description, step_type) VALUES ('Informar a operadores sus nuevas desviaciones de referencia.', 2);
INSERT INTO event_managment.t_002_steps (description, step_type) VALUES ('Si se requiere adicionar tarea, buscar una ruta para extraer vehículo.', 2);
INSERT INTO event_managment.t_002_steps (description, step_type) VALUES ('Si se ingresaron adicionales, registrar en bitácora.', 2);
INSERT INTO event_managment.t_002_steps (description, step_type) VALUES ('Hacer seguimiento a las instrucciones dadas.', 2);
INSERT INTO event_managment.t_002_steps (description, step_type) VALUES ('Aplicar estrategias de regulación.', 2);
INSERT INTO event_managment.t_002_steps (description, step_type) VALUES ('Informar al despacho de Concesionarios, los cambios de ruta.', 2);
INSERT INTO event_managment.t_002_steps (description, step_type) VALUES ('Si vehículo ya está operando, informar a operador cambio de ruta.', 2);
INSERT INTO event_managment.t_002_steps (description, step_type) VALUES ('Si hay cancelación de ruta, informar a despacho y a usuarios.', 2);
INSERT INTO event_managment.t_002_steps (description, step_type) VALUES ('Registrar en bitácora.', 2);
INSERT INTO event_managment.t_002_steps (description, step_type) VALUES ('Invalidar todos los viajes de la tarea (NO cancelar tarea).', 2);
INSERT INTO event_managment.t_002_steps (description, step_type) VALUES ('Ajustar frecuencia de la(s) línea(s) (VEHÍCULO FALTANTE).', 2);
INSERT INTO event_managment.t_002_steps (description, step_type) VALUES ('Aplicar estrategias de regulación.', 2);
INSERT INTO event_managment.t_002_steps (description, step_type) VALUES ('De ser suficiente, aplicar el EITL a los vehículos.', 2);
INSERT INTO event_managment.t_002_steps (description, step_type) VALUES ('Informar vía texto si es necesario los sobrepasos.', 2);
INSERT INTO event_managment.t_002_steps (description, step_type) VALUES ('Dar instrucciones a operador, vía texto, para adelantarlo o atrasarlo.', 2);
INSERT INTO event_managment.t_002_steps (description, step_type) VALUES ('Si el caso es muy crítico, reposicionar vehículos considerando demanda usuarios.', 2);
INSERT INTO event_managment.t_002_steps (description, step_type) VALUES ('Registrar en bitácora.', 2);
INSERT INTO event_managment.t_002_steps (description, step_type) VALUES ('Aplicar estrategias de regulación.', 2);
INSERT INTO event_managment.t_002_steps (description, step_type) VALUES ('Si es incumplimiento, atenderlo con INCUMPLIMIENTO.', 2);
INSERT INTO event_managment.t_002_steps (description, step_type) VALUES ('Verificar con personal de control en vía que el vehículo esté operando.', 2);
INSERT INTO event_managment.t_002_steps (description, step_type) VALUES ('Si vehículo está operando, definir con OMEGA la necesidad de que continúe y retirarlo lo antes posible.', 2);
INSERT INTO event_managment.t_002_steps (description, step_type) VALUES ('Si vehículo continúa, registrar en bitácora y en la plantilla de control de actividades.', 2);
INSERT INTO event_managment.t_002_steps (description, step_type) VALUES ('Hacer seguimiento al vehículo.', 2);
INSERT INTO event_managment.t_002_steps (description, step_type) VALUES ('Aplicar estrategias de regulación.', 2);
INSERT INTO event_managment.t_002_steps (description, step_type) VALUES ('Realizar la gestión pertinente del tipo de mensaje, previa a respuesta.', 2);
INSERT INTO event_managment.t_002_steps (description, step_type) VALUES ('Comunicarse vía texto o en caso de ser necesario usar la vía telefónica, con el operador para resolverle.', 2);
INSERT INTO event_managment.t_002_steps (description, step_type) VALUES ('Informar al despacho en caso que sea necesario.', 2);
INSERT INTO event_managment.t_002_steps (description, step_type) VALUES ('Registrar en bitácora de ser necesario.', 2);
INSERT INTO event_managment.t_002_steps (description, step_type) VALUES ('Si hay vehículos empaquetados, atenderlo como VEHÍCULOS EMPAQUETADOS.', 2);
INSERT INTO event_managment.t_002_steps (description, step_type) VALUES ('Si es conveniente la desviación horaria, NO afectó la ruta.', 2);
INSERT INTO event_managment.t_002_steps (description, step_type) VALUES ('Si es adelantó, enviar vía texto: "disminuya su adelanto" al operador.', 2);
INSERT INTO event_managment.t_002_steps (description, step_type) VALUES ('Si es atraso, llamar a consultar la justificación del atraso.', 2);
INSERT INTO event_managment.t_002_steps (description, step_type) VALUES ('Si atraso es justificado, apoyar operador con instrucción a otros vehículos.', 2);
INSERT INTO event_managment.t_002_steps (description, step_type) VALUES ('Si desviación es cercano a tiempo de ciclo, analizar estado de los viajes en plan de viaje.', 2);
INSERT INTO event_managment.t_002_steps (description, step_type) VALUES ('Sólo si atraso > 50% de intervalo y paradas próximas han sido atendidas o hay un vehículo detrás del atrasado, reposicionar.', 2);
INSERT INTO event_managment.t_002_steps (description, step_type) VALUES ('Registrar en bitácora de ser necesario.', 2);

INSERT INTO event_managment.t_002_protocols (category, step, step_order) VALUES (1, 49, 1);
INSERT INTO event_managment.t_002_protocols (category, step, step_order) VALUES (1, 50, 2);
INSERT INTO event_managment.t_002_protocols (category, step, step_order) VALUES (1, 51, 3);
INSERT INTO event_managment.t_002_protocols (category, step, step_order) VALUES (6, 52, 1);
INSERT INTO event_managment.t_002_protocols (category, step, step_order) VALUES (6, 53, 2);
INSERT INTO event_managment.t_002_protocols (category, step, step_order) VALUES (6, 54, 3);
INSERT INTO event_managment.t_002_protocols (category, step, step_order) VALUES (6, 55, 4);
INSERT INTO event_managment.t_002_protocols (category, step, step_order) VALUES (6, 56, 5);
INSERT INTO event_managment.t_002_protocols (category, step, step_order) VALUES (6, 57, 6);
INSERT INTO event_managment.t_002_protocols (category, step, step_order) VALUES (6, 58, 7);
INSERT INTO event_managment.t_002_protocols (category, step, step_order) VALUES (6, 59, 8);
INSERT INTO event_managment.t_002_protocols (category, step, step_order) VALUES (6, 60, 9);
INSERT INTO event_managment.t_002_protocols (category, step, step_order) VALUES (6, 61, 10);
INSERT INTO event_managment.t_002_protocols (category, step, step_order) VALUES (6, 62, 11);
INSERT INTO event_managment.t_002_protocols (category, step, step_order) VALUES (7, 52, 1);
INSERT INTO event_managment.t_002_protocols (category, step, step_order) VALUES (7, 53, 2);
INSERT INTO event_managment.t_002_protocols (category, step, step_order) VALUES (7, 54, 3);
INSERT INTO event_managment.t_002_protocols (category, step, step_order) VALUES (7, 55, 4);
INSERT INTO event_managment.t_002_protocols (category, step, step_order) VALUES (7, 56, 5);
INSERT INTO event_managment.t_002_protocols (category, step, step_order) VALUES (7, 57, 6);
INSERT INTO event_managment.t_002_protocols (category, step, step_order) VALUES (7, 58, 7);
INSERT INTO event_managment.t_002_protocols (category, step, step_order) VALUES (7, 59, 8);
INSERT INTO event_managment.t_002_protocols (category, step, step_order) VALUES (7, 60, 9);
INSERT INTO event_managment.t_002_protocols (category, step, step_order) VALUES (7, 61, 10);
INSERT INTO event_managment.t_002_protocols (category, step, step_order) VALUES (7, 62, 11);
INSERT INTO event_managment.t_002_protocols (category, step, step_order) VALUES (8, 63, 1);
INSERT INTO event_managment.t_002_protocols (category, step, step_order) VALUES (8, 64, 2);
INSERT INTO event_managment.t_002_protocols (category, step, step_order) VALUES (8, 65, 3);
INSERT INTO event_managment.t_002_protocols (category, step, step_order) VALUES (8, 66, 4);
INSERT INTO event_managment.t_002_protocols (category, step, step_order) VALUES (8, 67, 5);
INSERT INTO event_managment.t_002_protocols (category, step, step_order) VALUES (8, 68, 6);
INSERT INTO event_managment.t_002_protocols (category, step, step_order) VALUES (8, 69, 7);
INSERT INTO event_managment.t_002_protocols (category, step, step_order) VALUES (10, 63, 1);
INSERT INTO event_managment.t_002_protocols (category, step, step_order) VALUES (10, 64, 2);
INSERT INTO event_managment.t_002_protocols (category, step, step_order) VALUES (10, 65, 3);
INSERT INTO event_managment.t_002_protocols (category, step, step_order) VALUES (10, 66, 4);
INSERT INTO event_managment.t_002_protocols (category, step, step_order) VALUES (10, 67, 5);
INSERT INTO event_managment.t_002_protocols (category, step, step_order) VALUES (10, 68, 6);
INSERT INTO event_managment.t_002_protocols (category, step, step_order) VALUES (10, 69, 7);
INSERT INTO event_managment.t_002_protocols (category, step, step_order) VALUES (12, 63, 1);
INSERT INTO event_managment.t_002_protocols (category, step, step_order) VALUES (12, 64, 2);
INSERT INTO event_managment.t_002_protocols (category, step, step_order) VALUES (12, 65, 3);
INSERT INTO event_managment.t_002_protocols (category, step, step_order) VALUES (12, 66, 4);
INSERT INTO event_managment.t_002_protocols (category, step, step_order) VALUES (12, 67, 5);
INSERT INTO event_managment.t_002_protocols (category, step, step_order) VALUES (12, 68, 6);
INSERT INTO event_managment.t_002_protocols (category, step, step_order) VALUES (12, 69, 7);
INSERT INTO event_managment.t_002_protocols (category, step, step_order) VALUES (16, 77, 1);
INSERT INTO event_managment.t_002_protocols (category, step, step_order) VALUES (16, 78, 2);
INSERT INTO event_managment.t_002_protocols (category, step, step_order) VALUES (16, 79, 3);
INSERT INTO event_managment.t_002_protocols (category, step, step_order) VALUES (16, 80, 4);
INSERT INTO event_managment.t_002_protocols (category, step, step_order) VALUES (16, 81, 5);
INSERT INTO event_managment.t_002_protocols (category, step, step_order) VALUES (16, 82, 6);
INSERT INTO event_managment.t_002_protocols (category, step, step_order) VALUES (16, 83, 7);
INSERT INTO event_managment.t_002_protocols (category, step, step_order) VALUES (25, 84, 1);
INSERT INTO event_managment.t_002_protocols (category, step, step_order) VALUES (25, 85, 2);
INSERT INTO event_managment.t_002_protocols (category, step, step_order) VALUES (25, 86, 3);
INSERT INTO event_managment.t_002_protocols (category, step, step_order) VALUES (25, 87, 4);
INSERT INTO event_managment.t_002_protocols (category, step, step_order) VALUES (25, 88, 5);
INSERT INTO event_managment.t_002_protocols (category, step, step_order) VALUES (25, 89, 6);
INSERT INTO event_managment.t_002_protocols (category, step, step_order) VALUES (26, 84, 7);
INSERT INTO event_managment.t_002_protocols (category, step, step_order) VALUES (26, 85, 8);
INSERT INTO event_managment.t_002_protocols (category, step, step_order) VALUES (26, 86, 9);
INSERT INTO event_managment.t_002_protocols (category, step, step_order) VALUES (26, 87, 10);
INSERT INTO event_managment.t_002_protocols (category, step, step_order) VALUES (26, 88, 11);
INSERT INTO event_managment.t_002_protocols (category, step, step_order) VALUES (26, 89, 12);
INSERT INTO event_managment.t_002_protocols (category, step, step_order) VALUES (27, 90, 1);
INSERT INTO event_managment.t_002_protocols (category, step, step_order) VALUES (27, 91, 2);
INSERT INTO event_managment.t_002_protocols (category, step, step_order) VALUES (27, 92, 3);
INSERT INTO event_managment.t_002_protocols (category, step, step_order) VALUES (27, 93, 4);
INSERT INTO event_managment.t_002_protocols (category, step, step_order) VALUES (27, 94, 5);
INSERT INTO event_managment.t_002_protocols (category, step, step_order) VALUES (27, 95, 6);
INSERT INTO event_managment.t_002_protocols (category, step, step_order) VALUES (29, 96, 7);
INSERT INTO event_managment.t_002_protocols (category, step, step_order) VALUES (29, 97, 8);
INSERT INTO event_managment.t_002_protocols (category, step, step_order) VALUES (29, 98, 9);
INSERT INTO event_managment.t_002_protocols (category, step, step_order) VALUES (29, 99, 10);
INSERT INTO event_managment.t_002_protocols (category, step, step_order) VALUES (30, 96, 1);
INSERT INTO event_managment.t_002_protocols (category, step, step_order) VALUES (30, 97, 2);
INSERT INTO event_managment.t_002_protocols (category, step, step_order) VALUES (30, 98, 3);
INSERT INTO event_managment.t_002_protocols (category, step, step_order) VALUES (30, 99, 4);
INSERT INTO event_managment.t_002_protocols (category, step, step_order) VALUES (18, 100, 1);
INSERT INTO event_managment.t_002_protocols (category, step, step_order) VALUES (18, 101, 2);
INSERT INTO event_managment.t_002_protocols (category, step, step_order) VALUES (18, 102, 3);
INSERT INTO event_managment.t_002_protocols (category, step, step_order) VALUES (18, 103, 4);
INSERT INTO event_managment.t_002_protocols (category, step, step_order) VALUES (18, 104, 5);
INSERT INTO event_managment.t_002_protocols (category, step, step_order) VALUES (18, 105, 6);
INSERT INTO event_managment.t_002_protocols (category, step, step_order) VALUES (18, 106, 7);
INSERT INTO event_managment.t_002_protocols (category, step, step_order) VALUES (18, 107, 8);

INSERT INTO policies.t_002_users (account_name, is_active, password) VALUES ('Admin', '1' ,'b109f3bbbc244eb82441917ed06d618b9008dd09b3befd1b5e07394c706a8bb980b1d7785e5976ec049b46df5f1326af5a2ea6d103fd07c95385ffab0cacbc86');
